### ISSUE TITLE
Bugged Attack Speed on Sapphire Tools

### ISSUE THREAD

**Issue by JCaimo** [Orangejewce92/ojs_rpg_origins#1]
Hi :) I've been using this mod but found that some Sapphire Tools are extremely broken, for example, take a look at the Sapphire Axe:

 
![image](https://github.com/user-attachments/assets/b49b3a28-7cc0-4069-a899-507400ce23d9)

This Axe is better than any weapon in the mod, and many other mods... the same thing happens with the Pickaxe and the Hoe lol so I'm guessing it's bugged? It's even stronger that the Sapphire Sword...

If I'm given (minimal) indications on what the properties to edit these tools are, I can fork the repo and fix it.

I tried looking at some properties like attack_speed and similar stuff but couldn't find anything.

Thanks!

**Comment by Orangejewce92** [comment]
Woah! Also is this the forge or fabric version? Actually regardless I'll look into both and push an update out! Thanks for the report!

**Comment by Orangejewce92** [comment]
Hello, i have balanced all the tools and armor for both forge and fabric and am uploading right after this post!
