### ISSUE TITLE
Variant Human Skills and Feats Do Not Work as Intended

### ISSUE THREAD

**Issue by BigEPlays** [Orangejewce92/ojs_rpg_origins#2]
I've tested each and every feat and skilled as a variant human and none of them seem to work. Not sure if they work on a previous version or not, but is there a fix to this in the future we can expect?

**Comment by Orangejewce92** [comment]
the abilities are not working? and no sorry. due to bigger name companies destroying my name,  i have halted all of my work and stopped developing.  sorry for the inconvenience.
